# Generated by Django 3.0.3 on 2020-12-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinalStimData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.CharField(max_length=100)),
                ('contactNum', models.PositiveIntegerField()),
                ('currentVal', models.FloatField()),
                ('bodySide', models.CharField(max_length=100)),
                ('contactSymmetry', models.CharField(max_length=100)),
                ('signalingProcMethod', models.CharField(max_length=1000)),
                ('normalizationMethod', models.CharField(max_length=1000)),
                ('colormapOption', models.CharField(max_length=100)),
                ('imageData', models.BinaryField(null=True)),
                ('original', models.BooleanField(null=True)),
                ('sourceJobID', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('jobID',),
            },
        ),
    ]
