# Generated by Django 3.0.3 on 2021-02-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_values', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinalstimdata',
            name='caseNum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
